# Generated by Django 3.2.16 on 2026-02-27 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240818_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
